name: Android Build (Compose)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.2.2"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APKs (split by ABI)
        run: gradle :app:assembleDebug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks-debug
          path: |
            app/build/outputs/apk/debug/*.apk
